id: P009266
initial_creation_type: ocr
created_at: 25/03/2020
last_modified_at: 25/11/2021
source_metadata:
  id: bdr:W3CN4274
  title: བྱང་ཆུབ་སེམས་དཔའི་ས་དང་ཚོམས།
  author: ''
  volumes:
    aa005a21b6594bc6a6899b835b0a3765:
      image_group_id: I3CN4294
      title: ''
      volume_number: 1
      total_pages: 581
      base_file: v001.txt
