id: I4440BC03
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-25T02:27:54+00:00'
last_modified: '2022-06-08T09:47:56.631397+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W3CN4274
  title: བྱང་ཆུབ་སེམས་དཔའི་ས་དང་ཚོམས།
  author: ''
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
  base:
    BEE0:
      image_group_id: I3CN4294
      title: ''
      total_pages: 581
      order: 1
      base_file: BEE0.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
